### ISSUE TITLE
以Release模式运行APP的话，好像功能无法正常使用

### ISSUE THREAD

**Issue by Juice007** [hnxyzhw/UIButtonMutablieClick#1]
我实测了一下，不知道是为什么呢

**Comment by Juice007** [comment]
目前我采用这种方式：https://github.com/tianbinbin/Call_UIButton_Repeat/blob/master/OCSwift/OCSwift/UIButton%2BTBCustom.m     在Release模式下可以正常使用

**Comment by hnxyzhw** [comment]
好的，已修改。
